openapi: 3.0.3
info:
  title: Guild Wars 2 API
  description: >-
    The Guild Wars 2 API enables third-party applications to access data
    directly from the Guild Wars 2 servers.
  termsOfService: 'https://www.guildwars2.com/en/legal/guild-wars-2-content-terms-of-use/'
  version: '2'
externalDocs:
  description: Wiki Documentation
  url: 'https://wiki.guildwars2.com/wiki/API:Main'
servers:
  - url: 'https://api.guildwars2.com'
paths: { }

components:
  securitySchemes:
    token:
      type: http
      scheme: bearer
      description: API key to authorize requests
      in: header

  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    IdInt:
      type: integer
      description: Integer id of the resource
      example: 123
    IdString:
      type: string
      description: String id of the resource
      example: "ABCDE02B-8888-FEBA-1234-DE98765C7DEF"