openapi: 3.0.3
info:
  title: Guild Wars 2 API
  description: >-
    The Guild Wars 2 API enables third-party applications to access data
    directly from the Guild Wars 2 servers.
  termsOfService: 'https://www.guildwars2.com/en/legal/guild-wars-2-content-terms-of-use/'
  version: '2'
externalDocs:
  description: Wiki Documentation
  url: 'https://wiki.guildwars2.com/wiki/API:Main'
servers:
  - url: 'https://api.guildwars2.com'
paths: { }

components:
  schemas:
    IdInt:
      type: integer
      description: Integer id of the resource
      example: 123