logging:
    level:
        ROOT: INFO
application:
    rest:
        endpoints:
            account-category:
                account: '/v2/account'
                achievement: '${application.rest.endpoints.account-category.account}/achievements'
                bank: '${application.rest.endpoints.account-category.account}/bank'
                legendary-armory: '${application.rest.endpoints.account-category.account}/legendaryarmory'
            achievements-category:
                achievements: '/v2/achievements'
                categories: '${application.rest.endpoints.achievements-category.achievements}/categories'
                daily: '${application.rest.endpoints.achievements-category.achievements}/daily'
                groups: '${application.rest.endpoints.achievements-category.achievements}/groups'
                tomorrow: '${application.rest.endpoints.achievements-category.daily}/tomorrow'
            colors: '/v2/colors'
            guild-category:
                guild: '/v2/guild'
                guild-id: '${application.rest.endpoints.guild-category.guild}/{id}'
            home-category:
                nodes: '/v2/home/nodes'
            items: '/v2/items'
            minis: '/v2/minis'
            quaggans: '/v2/quaggans'
            raids: '/v2/raids'
            token-info: '/v2/tokeninfo'
            traits: '/v2/traits'
        config:
            base-url: 'https://api.guildwars2.com'
            connection-timeout: 1000
            enable-wiretap: false
            language: 'fr'
            page-maximum-size: 200
            read-timeout: 1000
            schema-version-date: '2022-11-12T00:00:00.000Z'
            write-timeout: 1000