application:
    rest:
        endpoints:
            account-category:
                account: '/v2/account'
                achievement: '${application.rest.endpoints.account-category.account}/achievements'
            achievements-category:
                achievements: '/v2/achievements'
                categories: '${application.rest.endpoints.achievements-category.achievements}/categories'
                daily: '${application.rest.endpoints.achievements-category.achievements}/daily'
                groups: '${application.rest.endpoints.achievements-category.achievements}/groups'
                tomorrow: '${application.rest.endpoints.achievements-category.daily}/tomorrow'
            colors: '/v2/colors'
            minis: '/v2/minis'
            quaggans: '/v2/quaggans'
        config:
            base-url: https://api.guildwars2.com
            connection-timeout: 1000
            enable-wiretap: false
            language: 'fr'
            page-maximum-size: 200
            read-timeout: 1000
            schema-version-date: '2022-11-12T00:00:00.000Z'
            write-timeout: 1000